name: mvvm
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.6.1
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  provider: ^6.0.5
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
